# Generated by Django 4.2.7 on 2025-12-02 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='flagged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='GCash transaction ID', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_id',
            field=models.CharField(blank=True, help_text='Webhook ID for idempotency', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('payment_refunded', 'Payment Refunded'), ('payment_verified', 'Payment Verified'), ('payment_flagged', 'Payment Flagged'), ('payment_disputed', 'Payment Disputed'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('refund_rejected', 'Refund Rejected'), ('webhook_received', 'Webhook Received'), ('receipt_generated', 'Receipt Generated'), ('receipt_sent', 'Receipt Sent')], max_length=50)),
                ('user_role', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action'], name='payments_pa_timesta_5a79d0_idx'), models.Index(fields=['payment', '-timestamp'], name='payments_pa_payment_59d208_idx')],
            },
        ),
    ]
