# Generated by Django 4.2.7 on 2025-12-07 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_payment_flag_reason_payment_flagged_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='GCash/PayPal reference number', max_length=100)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID if available', max_length=200)),
                ('screenshot', models.ImageField(help_text='Screenshot or image of payment proof', upload_to='payment_proofs/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from customer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from staff during verification')),
            ],
            options={
                'verbose_name': 'Payment Proof',
                'verbose_name_plural': 'Payment Proofs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='paymentauditlog',
            name='payments_pa_timesta_5a79d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentauditlog',
            name='payments_pa_payment_59d208_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='admin_override',
            field=models.BooleanField(default=False, help_text='Indicates if this action was an admin override'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentauditlog',
            name='action',
            field=models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('payment_cancelled', 'Payment Cancelled'), ('payment_refunded', 'Payment Refunded'), ('payment_verified', 'Payment Verified'), ('payment_flagged', 'Payment Flagged'), ('payment_disputed', 'Payment Disputed'), ('submitted_proof', 'Payment Proof Submitted'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('refund_rejected', 'Refund Rejected'), ('webhook_received', 'Webhook Received'), ('receipt_generated', 'Receipt Generated'), ('receipt_sent', 'Receipt Sent')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['timestamp'], name='payments_pa_timesta_86a1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['action'], name='payments_pa_action_5c6325_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['admin_override'], name='payments_pa_admin_o_238841_idx'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentproof', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_proofs', to=settings.AUTH_USER_MODEL),
        ),
    ]
