# Generated by Django 4.2.7 on 2025-12-07 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_remove_bill_penalty'),
        ('payments', '0003_paymentproof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for verification or rejection')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_override', models.BooleanField(default=False, help_text='Indicates if this action was an admin override')),
            ],
            options={
                'verbose_name': 'Payment Audit',
                'verbose_name_plural': 'Payment Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='billing.bill'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='reference_number',
            field=models.CharField(help_text='GCash reference number', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID if available', max_length=50),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['status'], name='payments_pa_status_c78898_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['submitted_at'], name='payments_pa_submitt_cc883a_idx'),
        ),
        migrations.AddField(
            model_name='paymentaudit',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payments.paymentproof'),
        ),
        migrations.AddField(
            model_name='paymentaudit',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proof_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentaudit',
            index=models.Index(fields=['timestamp'], name='payments_pa_timesta_d7436f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaudit',
            index=models.Index(fields=['action'], name='payments_pa_action_5ebd71_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentaudit',
            index=models.Index(fields=['admin_override'], name='payments_pa_admin_o_b935f2_idx'),
        ),
    ]
