# Generated by Django 4.2.7 on 2025-10-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('target_puroks', models.CharField(blank=True, help_text='Comma-separated purok numbers (e.g., 1,2,3) or leave blank for all', max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('due_date', models.DateField()),
                ('disconnection_date', models.DateField()),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('present_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_consumption', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('minimum_cubic_meters', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('rate_per_cubic_meter', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid')], default='unpaid', max_length=20)),
                ('is_overdue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billing_month'],
                'unique_together': {('customer', 'billing_month')},
            },
        ),
    ]
