# Generated by Django 4.2.7 on 2025-10-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterupdate',
            name='update_type',
            field=models.CharField(choices=[('Announcements', 'Announcements'), ('Emergency', 'Emergency'), ('Maintenance', 'Maintenance')], default='Announcements', max_length=20),
        ),
        migrations.AlterField(
            model_name='waterupdate',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
