# Generated by Django 4.2.7 on 2025-10-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_waterupdate_update_type_alter_waterupdate_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='penalty',
        ),
    ]
