# Generated by Django 4.2.7 on 2025-10-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='water_meter_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
