# Generated by Django 4.2.7 on 2025-10-05 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_middle_initial_user_water_meter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='created_user',
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('user_type', 'admin'), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
