# Generated by Django 4.2.7 on 2025-10-05 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_membershiprequest_created_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='created_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
